---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bookinfo
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./kustomize
  prune: true
  sourceRef:
    kind: GitRepository
    name: tsb
  targetNamespace: bookinfo
